#!/bin/bash

if [ -e "/usr/bin/sensors" ]; then
   # Requiert l'installation du paquet lm-sensors
   IFS=$' '
   while read -d $'\xBF' line; do
      unset temp_cpu temp_mb temp_core
      temp_cpu=$(echo $line | grep -ioP '^CPU Temperature:\K.*')
      temp_mb=$(echo $line | grep -ioP '^MB Temperature:\K.*')
      temp_core=$(echo $line | grep -ioP '^Core\s([0-9]+):.*')
      if [ ! -z "$temp_cpu" ]; then
	 temp_cpu=$(echo $temp_cpu | cut -d '+' -f2 | cut -d 'C' -f1)
	 echo " \${color}CPU\${alignr}\${color0}$temp_cpu"
      fi
      if [ ! -z "$temp_mb" ]; then
	 temp_mb=$(echo $temp_mb | cut -d '+' -f2 | cut -d 'C' -f1)
	 echo " \${color}Carte mère\${alignr}\${color0}$temp_mb"
      fi
      if [ ! -z "$temp_core" ]; then
	 while read -r detail; do
	    temp_core_nb=$(echo $detail | grep -Eo '[0-9]+' | head -1)
	    temp_core=$(echo $detail | cut -d '+' -f2 | cut -d 'C' -f1)
	    echo " \${color}Processeur $temp_core_nb\${alignr}\${color0}$temp_core"
	 done <<< "$temp_core"
      fi
      if [ -z "$temp_cpu" ] && [ -z "$temp_mb" ] && [ -z "$temp_core" ]; then
	 temp_device=$(echo $line | head -1)
	 unset temp_other
	 temp_other=$(echo $line | grep -ioP '^temp([0-9]+):.*' | head -1 | cut -d '+' -f2 | cut -d 'C' -f1)
	 if [ ! -z "$temp_other" ]; then
	    echo " \${color}$temp_device\${alignr}\${color0}$temp_other"
	 fi
      fi
   done < <(/usr/bin/sensors | awk -v RS='\n\n' '{printf "%s\xBF", $0}')
   unset IFS
fi

exit 0
